### ISSUE TITLE
Appending doesn't work when regex contains multiline

### ISSUE THREAD

**Issue by pkrudys** [nefrob/pr-description#18]
**Describe the bug**
Appending doesn't work when regex contains multiline.

https://github.com/nefrob/pr-description/issues/8 has been closed due to inactivity, but it still persists.

**To Reproduce**

Add following step to github action:
```
            - name: Update PR Description
              uses: nefrob/pr-description@v1.1.1
              with:
                  content: "<!-- start regex match -->Test\ntest\ntest<!-- end regex match -->"
                  regex: "<!-- start regex match -->.*?<!-- end regex match -->"
                  token: ${{ secrets.GITHUB_TOKEN }}
```
and run it several times. The issue results in multiple `<!-- start regex match -->Test\ntest\ntest<!-- end regex match -->` occurences, each appended to the previous one.
```
## Title
Hello there!
This change is about something entirely new. 

### More info
New line written manually. 
Also new line written manually...<!-- start regex match -->Test
test
test<!-- end regex match --><!-- start regex match -->Test
test
test<!-- end regex match --><!-- start regex match -->Test
test
test<!-- end regex match --><!-- start regex match -->Test
test
test<!-- end regex match -->
```

**Expected behavior**
I expect PR description to NOT be modified, since I am replacing value with the same value.

**Screenshots**
![image](https://github.com/nefrob/pr-description/assets/88082148/a015ddf1-8c41-403b-be50-30287d4d7227)

**Additional info**
What I've also observed, is that when you skip "end" regex match, like this:
```
            - name: Update PR Description
              uses: nefrob/pr-description@v1.1.1
              with:
                  content: "<!-- start regex match -->Test\ntest\ntest"
                  regex: "<!-- start regex match -->.*"
                  token: ${{ secrets.GITHUB_TOKEN }}
```
and run it multiple times, it doesn't just append the content, but replaces the first occurence of regex match until newline sign (so replaces `<!-- start regex match -->Test` with `<!-- start regex match -->Test\ntest\ntest`. 

Running the action 3 times results in following:
```
...
Also new line written manually...<!-- start regex match -->Test
test
test
test
test
test
test
```
