### ISSUE TITLE
How do you add newlines with this action?

### ISSUE THREAD

**Issue by misterjohannesson** [nefrob/pr-description#4]
Usage

```
 - name: Sets resolver text
        uses: nefrob/pr-description@v1.1.0
        with:
          content: "${{ github.event.pull_request.body }}\n\nFixes AB#${{ steps.extract_itemid.outputs.itemid }}"
          token: ${{ secrets.GITHUB_TOKEN }}
```

Expected out would be an appended text string with two newlines. 
```
this is the PR description.

Fixes AD#123
```

But the "\n" are completely ignored 
The text ends up like the following

```
this is the PR description.Fixes AD#123
```

**Comment by nefrob** [comment]
Hmm interesting. I'll take a look if I have time later this week.

**Comment by nefrob** [comment]
Ah I think this was due to `core.getInput` trimming the inputs by default and maybe`${{ github.event.pull_request.body }}` being empty in your example above. If this is the case, you were still getting the existing PR body since the fallback for no regex match with PR body was to append the new content to the existing body (pulled in the action not from the provided content in this case). You could echo the value of `${{ github.event.pull_request.body }}` on your action to validate my assumption.

I have updated the whitespace issue and made the append mode configurable here: https://github.com/nefrob/pr-description/pull/5.

You can test the change by setting the action used by your step to 

```yaml
uses: nefrob/pr-description@nefrob/fix-newlines-not-respected
with:
  content: "${{ github.event.pull_request.body }}\n\nFixes AB#${{ steps.extract_itemid.outputs.itemid }}"
  regex: ".*"
  token: ${{ secrets.GITHUB_TOKEN }}
```

Barring any issues I will get this fix released.
