### ISSUE TITLE
appendContentOnMatchOnly is not a valid input

### ISSUE THREAD

**Issue by angelod1as** [nefrob/pr-description#7]
## What's happening

I'm following the docs and did:

```
name: "Update PR description"

on:
  pull_request:

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Do action
        uses: nefrob/pr-description@v1.1.0
        with:
          content: ${{github.event.number}}
          regex: "PR_NUMBER"
          regexFlags: i
          token: ${{ secrets.GITHUB_TOKEN }}
          appendContentOnMatchOnly: true      <---- here
```

which resulted in:

![image](https://github.com/nefrob/pr-description/assets/13950513/ccba6c51-cafd-439c-b609-1b7a75affcd9)

Also, my content is appended to the description even with the property `true`

## Expected:

The property should work.
