### ISSUE TITLE
I am following your example to replace the description but it always appends on new commits

### ISSUE THREAD

**Issue by bads77** [nefrob/pr-description#8]
my Pull request template

```
<!-- Description start-->
description goes here
<!-- Description end -->
```

my github action:

```
name: DEV | Update PR description

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Override PR description
        uses: nefrob/pr-description@v1.1.0
        with:
          content: |
            <!-- Description start-->
            ## Describe your changes

            ## Issue ticket number and link

            ## Checklist before requesting a review
            - [ ] I have performed a self-review of my code
            - [ ] I have tested my changes locally
            - [ ] I have ran pulumi up for my infra changes with prod profile
            - [ ] I have updated the database tables with the new changes
            - [ ] I have updated the environment variables and secrets  
            - [ ] I have applied the manual cluster changes if any
            - [ ] I have updated the dns configuration if any
            - [ ] I have updated the integrations settings if any

            ## Any comments/requests for reviewer?

            ### Please follow this [review ladder](https://www.netlify.com/blog/2020/03/05/feedback-ladders-how-we-encode-code-reviews-at-netlify/) for code reviews
            <!-- Description end -->

          regex: "<!-- Description start-->.*?<!-- Description end-->"
          regexFlags: ims

          token: ${{ secrets.GITHUB_TOKEN }}

```

As soon as a new commit is added to the PR, here is what my description looks like:

```
<!-- Description start-->
## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes locally
- [ ] I have ran pulumi up for my infra changes with prod profile
- [ ] I have updated the database tables with the new changes
- [ ] I have updated the environment variables and secrets  
- [ ] I have applied the manual cluster changes if any
- [ ] I have updated the dns configuration if any
- [ ] I have updated the integrations settings if any

## Any comments/requests for reviewer?

### Please follow this [review ladder](https://www.netlify.com/blog/2020/03/05/feedback-ladders-how-we-encode-code-reviews-at-netlify/) for code reviews
<!-- Description end --><!-- Description start-->
## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes locally
- [ ] I have ran pulumi up for my infra changes with prod profile
- [ ] I have updated the database tables with the new changes
- [ ] I have updated the environment variables and secrets  
- [ ] I have applied the manual cluster changes if any
- [ ] I have updated the dns configuration if any
- [ ] I have updated the integrations settings if any

## Any comments/requests for reviewer?

### Please follow this [review ladder](https://www.netlify.com/blog/2020/03/05/feedback-ladders-how-we-encode-code-reviews-at-netlify/) for code reviews
<!-- Description end -->
```
